"""create tasks table

Revision ID: 85ea1ffb6d00
Revises: 8409c5a4dd86
Create Date: 2025-04-17 19:39:52.305107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ea1ffb6d00'
down_revision: Union[str, None] = '8409c5a4dd86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
